#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             diff_csv.txt  diff_out.txt vcs_equilibrate_res.csv
#
# Create a symbolic link to electrodeCell, if none exists already
#

PROG_EXE=./LiCoO2_Cathode_1  
if test ! -x ${PROG_EXE}  ; then
  echo 'ERROR: ' ${PROG_EXE} ' executable can not be found'
  exit -1
fi

#################################################################
#
#################################################################

$PROG_EXE   > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "$PROG_EXE returned with bad status, $retnStat, check output"
fi


diff good_out.txt out.txt > diff_out.txt
retnStat_txt=$?


if test $retnStat_txt = "0"
then
  echo "Successful test comparison on "`pwd`
else
  echo "Unsuccessful test comparison on "`pwd` " test"
fi

#
# return 0 for no errors, 1 for errors
#
exit 0

