#!/bin/sh
#
#
#
CANTERA_INSTALL_DIR=/home/hea/arch/linux64_gcc472/cantera_trunk_dbg
export CANTERA_INSTALL_DIR
#
CANTERA_ROOT=/home/hea/Cantera/cantera_trunk
export CANTERA_ROOT
#
CANTERA_APPS_INSTALL_DIR="${CANTERA_INSTALL_DIR}/apps_dbg"
export CANTERA_APPS_INSTALL_DIR
#
#
#  BUILD_WITH_F2C is optional on linux. 
#
export BUILD_WITH_F2C='n'
#
#
#
# -DDEBUG_MODE
# -DDEBUG_HKM
# -DDO_INIT_CALC
#CXXFLAGS="-g -Wall -DDEBUG_HKM"
CXXFLAGS="-g -Wall -DDEBUG_MODE"
export CXXFLAGS
#
LCXX_END_LIBS=" -lgfortran"
export LCXX_END_LIBS
#
# Specify the fortran compiler, because some libraries are
# written in fortran. This is used to find the libraries
# to link against
#
#FFLAGS="-g -DDEBUG_HKM  -fno-second-underscore"
FFLAGS="-g -fno-second-underscore"
export FFLAGS
#
#  MPIHOME on anode
#
export MPIHOME=/usr/lib64/mpi/gcc/openmpi

MPICXX=${MPIHOME}/bin/mpiCC
export MPICXX

MPICC=${MPIHOME}/bin/mpicc
export MPICC

MPIF77=${MPIHOME}/bin/mpif77
export MPIF77

CXX_DEPENDS='/usr/lib64/mpi/gcc/openmpi/bin/mpiCC -MM'
# CXX_DEPENDS="${CXX}  -MM"
echo CXX_DEPENDS = $CXX_DEPENDS
export CXX_DEPENDS 
#
#
TRILINOS_INSTALL_DIR="/shared/CAEBAT/tpl/opt/bin/trilinos-11.0.4"
export TRILINOS_INSTALL_DIR

DO_MPI='y'
export DO_MPI

#
MAKE=gmake
export MAKE
#
./preconfig
