#!/bin/sh

TESTNAME =  FeS2_1_electrode_rxn

BLESSED_FILES =  FeS2_1_electrode.xml  FeS2.xml  Li3Fe2S4.xml  LiKCl_Margules_trans.xml \
                  LiKCl_recipmoltenSalt_trans.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub


rebaseline::
	cp  polarizationData.csv  polarizationData_blessed.csv
