#/bin/sh

all:
	cd src; $(MAKE)

clean:
	cd src; $(RM) .depends ; $(MAKE) clean

dist_clean:
	cd src; $(RM) .depends ; $(MAKE) dist_clean

clean_dist:
	cd src; $(RM) .depends ; $(MAKE) clean_dist

clean_test_flags:
	cd src; $(RM) .depends ; $(MAKE) clean_test_flags

depends:
	cd src; $(MAKE) depends

install:
	cd src; $(MAKE) install

test:

# end of file

