#!/bin/sh
#
#
eCode=0
temp_success="1"
/bin/rm  -f  dout.txt err_dout.txt \
             vcs_equilibrate_res*.csv \
             diff_csv*.txt  diff_dout.txt

#################################################################
#
#################################################################

CO2_solubility -d 9  > dout.txt 2>err_dout.txt
retnStat=$?
if test $retnStat != "0" 
then
  echo "CO2_solubility returned with bad status, $retnStat, check output"
  exit 0
fi

diff good_dout.txt dout.txt  > diff_dout.txt
retnStat_txt=$?

csvdiff -a 1.0E-50 vcs_equilibrate_blessed.csv vcs_equilibrate_res.csv > diff_csv.txt
retnStat_csv=$?

csvdiff -a 1.0E-50 vcs_equilibrate_blessed_1.csv vcs_equilibrate_res_1.csv > diff_csv_1.txt
retnStat_csv_1=$?

csvdiff -a 1.0E-50 vcs_equilibrate_blessed_2.csv vcs_equilibrate_res_2.csv > diff_csv_2.txt
retnStat_csv_2=$?

csvdiff -a 1.0E-50 vcs_equilibrate_blessed_3.csv vcs_equilibrate_res_3.csv > diff_csv_3.txt
retnStat_csv_3=$?

csvdiff -a 1.0E-50 vcs_equilibrate_blessed_4.csv vcs_equilibrate_res_4.csv > diff_csv_4.txt
retnStat_csv_4=$?

eCode=0
retnTotal=1
if test $retnStat_csv = "0"  -a   $retnStat_csv_1 = "0"
then
  if test $retnStat_csv_2 = "0"
  then
    if test $retnStat_csv_3 = "0"
    then
      if test $retnStat_csv_4 = "0"
      then
        retnTotal=0
      fi
    fi
  fi
fi



if test $retnTotal = "0"  
then
  echo "Successful test comparison on "`pwd`
  if [ $retnStat_txt != "0" ]
  then
     echo "   But, text output files have differences. See diff_dout.txt"
  fi
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnTotal != "0"  
  then
     echo "      csv files are different - see diff_csv.txt"
  fi
  if test $retnStat_txt != "0" 
  then
     echo "      And, text output files have differences. See diff_dout.txt"
  fi
fi
#
# return 0 for no errors, 1 for errors
#
exit $eCode

