#!/bin/sh

TESTNAME = Li_LiCl_electrode_rxn

BLESSED_FILES =   problem_setup.sh  LiSi_2_electrode.xml  LiKCl_Margules.xml \
    LiKCl_recipmoltenSalt.xml    metal_Li_LiCl_electrons.xml

include ../Makefile_sub



