#!/bin/sh

TESTNAME =   NewmanFeS2Electrode_rxn

BLESSED_FILES = FeS2_A.xml  FeS2_B.xml  FeS2_electrode.xml  LiKCl_Margules.xml  LiKCl_recipmoltenSalt.xml\
                Li_Liquid.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub


