#!/bin/sh

TESTNAME =  LiSi_3_LiCl_electrode_rxn

BLESSED_FILES =   problem_setup.sh  Li12Si7.xml  LiKCl_Margules.xml  LiKCl_recipmoltenSalt.xml \
          LiSi_3_electrode.xml  metal_Li_LiCl_electrons.xml  Si_Solid.xml


include ../Makefile_sub



