#!/bin/sh
#
#
if test ! -f cttables ; then
  if test -f ../../src/cttables ; then
    ln -s ../../src/cttables .
  fi
fi
/bin/rm -rf out.txt diff_out.txt
cttables  cttables.inp > out.txt
diff good_out.txt out.txt > diff_out.txt
retnStat=$?
if [ $retnStat = "0" ]
  then
    echo "Successful diff comparison of "`pwd`
  else
    echo "Unsuccessful diff comparison of "`pwd`". See diff_out.txt"
fi
