#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output.txt outputa.txt
######################################################################

ctv=2.1a1
realtest="1"
if test ! $ctv = "1.8_liquidTransportDevelop"
then
   ./runtest_old
   exit 0
fi

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./ionizedGasEquil > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "ionizedGasEquil returned with bad status, $retnStat, check output"
fi

names=gas*Data.csv
names_b=gas*Data_blessed.csv
data=($names)
data_b=($names_b)

retnTotal=0
for((i=0;i<${#data[*]};i++))
  do
  csvdiff -r 1.0E-5 ${data_b[$i]} ${data[$i]} > diff_${data[$i]}
  csvStat[$i]=$?
  if test ${csvStat[$i]} != "0"
      then
      retnTotal=1
      echo "Unsuccessful test comparison on "`pwd`
      echo "      csv files are different - see diff_"${data[$i]}
  fi
done
diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?


if [ $retnTotal = "0" ] #&& [ $txtStat = "0" ]
then
  echo "successful test comparison on "`pwd`" test"
else
  echo "unsuccessful test comparison on "`pwd`" test see gasData_txtdiff.txt and gasData_csvdiff.txt"
  echo "FAILED" > csvCode.txt
  temp_success="0"
fi

