#/bin/sh

all:

clean:
	cd silaneMech;                                        $(MAKE) clean
	cd fixedChemPot;                                      $(MAKE) clean
	cd heliumAir; ./cleanup
	cd issPhase; ./cleanup
	cd DHphase; ./cleanup
	cd hacaSurf;                                          $(MAKE) clean
	cd diamondSurf; ./cleanup
	cd airNASA9; ./cleanup
	cd H2_electrode_rxn;                                  $(MAKE) clean
	cd Al_electrode_rxn; ./cleanup
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                   $(MAKE) -s clean
	cd HMW_NaCl_sp_test;                                  $(MAKE) -s clean
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) -s clean
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) -s clean
	cd LiSi_LiCl_electrode_rxn; ./cleanup
	cd LiSi_0_LiCl_electrode_rxn; ./cleanup
	cd LiSi_2_LiCl_electrode_rxn; ./cleanup
	cd LiSi_3_LiCl_electrode_rxn; ./cleanup
	cd LiMetal_LiIon_electrode_rxn; ./cleanup
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                 $(MAKE) -s clean
	cd FeS2_electrode_rxn_1;                              $(MAKE) -s clean
	cd FeS2_electrode_rxn_2;                              $(MAKE) -s clean
	cd FeS2_electrode_rxn_3;                              $(MAKE) -s clean
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) -s clean

depends:

install:

test:
	cd silaneMech;                                        $(MAKE) -s test
	cd fixedChemPot;                                      $(MAKE) -s test
	cd heliumAir; ./runtest
	cd issPhase; ./runtest
	cd DHphase; ./runtest
	cd hacaSurf;                                          $(MAKE) -s test
	cd diamondSurf; ./runtest
	cd airNASA9; ./runtest
	cd H2_electrode_rxn;                                  $(MAKE) -s test
	cd Al_electrode_rxn; ./runtest
	cd Zn_electrode_rxn; ./runtest
	cd KCl_solid_test; ./runtest
	cd NaCl_solid_test;                                   $(MAKE) -s test
	cd HMW_NaCl_sp_test;                                  $(MAKE) -s test
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) -s test
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) -s test
	cd LiSi_LiCl_electrode_rxn; ./runtest
	cd LiSi_0_LiCl_electrode_rxn; ./runtest
	cd LiSi_2_LiCl_electrode_rxn; ./runtest
	cd LiSi_3_LiCl_electrode_rxn; ./runtest
	cd LiMetal_LiIon_electrode_rxn; ./runtest
	cd MCMBAnode_LiIon_electrode_rxn; ./runtest
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./runtest
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./runtest
	cd FeS_electrode_rxn;                                 $(MAKE) -s test
	cd FeS2_electrode_rxn_1;                              $(MAKE) -s test
	cd FeS2_electrode_rxn_2;                              $(MAKE) -s test
	cd FeS2_electrode_rxn_3;                              $(MAKE) -s test
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) -s test

rebaseline:
	cd silaneMech;                                        $(MAKE) rebaseline
	cd fixedChemPot;                                      $(MAKE) rebaseline
	cd heliumAir; ./rebaseline
	cd issPhase; ./rebaseline
	cd DHphase; ./rebaseline
	cd hacaSurf;                                          $(MAKE) rebaseline
	cd diamondSurf; ./rebaseline
	cd airNASA9; ./rebaseline
	cd H2_electrode_rxn;                                  $(MAKE) rebaseline
	cd Al_electrode_rxn; ./rebaseline
	cd Zn_electrode_rxn; ./rebaseline
	cd KCl_solid_test; ./rebaseline
	cd NaCl_solid_test;                                   $(MAKE) rebaseline
	cd HMW_NaCl_sp_test;                                  $(MAKE) rebaseline
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) rebaseline
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) rebaseline
	cd LiSi_LiCl_electrode_rxn; ./rebaseline
	cd LiSi_0_LiCl_electrode_rxn; ./rebaseline
	cd LiSi_2_LiCl_electrode_rxn; ./rebaseline
	cd LiSi_3_LiCl_electrode_rxn; ./rebaseline
	cd LiMetal_LiIon_electrode_rxn; ./rebaseline
	cd MCMBAnode_LiIon_electrode_rxn; ./rebaseline
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./rebaseline
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./rebaseline
	cd FeS_electrode_rxn;                                 $(MAKE) rebaseline
	cd FeS2_electrode_rxn_1;                              $(MAKE) rebaseline
	cd FeS2_electrode_rxn_2;                              $(MAKE) rebaseline
	cd FeS2_electrode_rxn_3;                              $(MAKE) rebaseline
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) rebaseline


clean_dist:
	cd silaneMech;                                        $(MAKE) clean_dist
	cd fixedChemPot;                                      $(MAKE) clean_dist
	cd heliumAir; ./cleanup
	cd issPhase; ./cleanup
	cd DHphase; ./cleanup
	cd hacaSurf;                                          $(MAKE) clean_dist
	cd diamondSurf; ./cleanup
	cd airNASA9; ./cleanup
	cd H2_electrode_rxn;                                  $(MAKE) clean_dist
	cd Al_electrode_rxn; ./cleanup
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                    $(MAKE) -s clean_dist
	cd HMW_NaCl_sp_test;                                   $(MAKE) -s clean_dist
	cd HMW_NaKCl_EQ3_test;                                 $(MAKE) -s clean_dist
	cd Li_LiCl_electrode_rxn ;                             $(MAKE) -s clean_dist
	cd LiSi_LiCl_electrode_rxn; ./cleanup
	cd LiSi_0_LiCl_electrode_rxn; ./cleanup
	cd LiSi_2_LiCl_electrode_rxn; ./cleanup
	cd LiSi_3_LiCl_electrode_rxn; ./cleanup
	cd LiMetal_LiIon_electrode_rxn; ./cleanup
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                  $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_1;                               $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_2;                               $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_3;                               $(MAKE) -s clean_dist
	cd NewmanFeS2Electrode_rxn;                            $(MAKE) -s clean_dist

clean_test:
	cd silaneMech;                                         $(MAKE) -s clean_test
	cd fixedChemPot;                                       $(MAKE) clean_test
	cd heliumAir; ./cleanup
	cd issPhase; ./cleanup
	cd DHphase; ./cleanup
	cd hacaSurf;                                           $(MAKE) clean_test
	cd diamondSurf; ./cleanup
	cd airNASA9; ./cleanup
	cd H2_electrode_rxn; ./cleanup
	cd Al_electrode_rxn; ./cleanup
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                    $(MAKE) -s clean_test
	cd HMW_NaCl_sp_test;                                   $(MAKE) -s clean_test
	cd HMW_NaKCl_EQ3_test;                                 $(MAKE) -s clean_test
	cd Li_LiCl_electrode_rxn ;                             $(MAKE) -s clean_test
	cd LiSi_LiCl_electrode_rxn; ./cleanup
	cd LiSi_0_LiCl_electrode_rxn; ./cleanup
	cd LiSi_2_LiCl_electrode_rxn; ./cleanup
	cd LiSi_3_LiCl_electrode_rxn; ./cleanup
	cd LiMetal_LiIon_electrode_rxn; ./cleanup
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                  $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_1;                               $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_2;                               $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_3;                               $(MAKE) -s clean_test
	cd NewmanFeS2Electrode_rxn;                            $(MAKE) -s clean_test

clean_test_flags:
	cd silaneMech;                                         $(MAKE) -s clean_test_flags
	cd fixedChemPot;                                       $(MAKE) -s clean_test_flags
	cd heliumAir; ./cleanup
	cd issPhase; ./cleanup
	cd DHphase; ./cleanup
	cd hacaSurf;                                           $(MAKE) clean_test_flags
	cd diamondSurf; ./cleanup
	cd airNASA9; ./cleanup
	cd H2_electrode_rxn;                                   $(MAKE) clean_test_flags
	cd Al_electrode_rxn; ./cleanup
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                    $(MAKE) -s clean_test_flags
	cd HMW_NaCl_sp_test;                                   $(MAKE) -s clean_test_flags
	cd HMW_NaKCl_EQ3_test;                                 $(MAKE) -s clean_test_flags
	cd Li_LiCl_electrode_rxn ;                             $(MAKE) -s clean_test_flags
	cd LiSi_LiCl_electrode_rxn; ./cleanup
	cd LiSi_0_LiCl_electrode_rxn; ./cleanup
	cd LiSi_2_LiCl_electrode_rxn; ./cleanup
	cd LiSi_3_LiCl_electrode_rxn; ./cleanup
	cd LiMetal_LiIon_electrode_rxn; ./cleanup
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                  $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_1;                               $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_2;                               $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_3;                               $(MAKE) -s clean_test_flags
	cd NewmanFeS2Electrode_rxn;                            $(MAKE) -s clean_test_flags


