#/bin/sh

all:

depends:

install:

test:
	cd silaneMech;                                        $(MAKE) -s test
	cd fixedChemPot;                                      $(MAKE) -s test
	cd heliumAir;                                         $(MAKE) -s test
	cd issPhase;                                          $(MAKE) -s test
	cd DHphase;                                           $(MAKE) -s test
	cd hacaSurf;                                          $(MAKE) -s test
	cd diamondSurf;                                       $(MAKE) -s test
	cd airNASA9;                                          $(MAKE) -s test
	cd H2_electrode_rxn;                                  $(MAKE) -s test
	cd Al_electrode_rxn;                                  $(MAKE) -s test
	cd Zn_electrode_rxn; ./runtest
	cd KCl_solid_test; ./runtest
	cd NaCl_solid_test;                                   $(MAKE) -s test
	cd HMW_NaCl_sp_test;                                  $(MAKE) -s test
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) -s test
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) -s test
	cd LiSi_LiCl_electrode_rxn;                           $(MAKE) -s test
	cd LiSi_0_LiCl_electrode_rxn;                         $(MAKE) -s test
	cd LiSi_2_LiCl_electrode_rxn;                         $(MAKE) -s test
	cd LiSi_3_LiCl_electrode_rxn;                         $(MAKE) -s test
	cd LiMetal_LiIon_electrode_rxn;                       $(MAKE) -s test
	cd MCMBAnode_LiIon_electrode_rxn; ./runtest
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./runtest
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./runtest
	cd FeS_electrode_rxn;                                 $(MAKE) -s test
	cd FeS2_electrode_rxn_1;                              $(MAKE) -s test
	cd FeS2_electrode_rxn_2;                              $(MAKE) -s test
	cd FeS2_electrode_rxn_3;                              $(MAKE) -s test
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) -s test

rebaseline:
	cd silaneMech;                                        $(MAKE) rebaseline
	cd fixedChemPot;                                      $(MAKE) rebaseline
	cd heliumAir;                                         $(MAKE) rebaseline
	cd issPhase;                                          $(MAKE) rebaseline
	cd DHphase;                                           $(MAKE) rebaseline
	cd hacaSurf;                                          $(MAKE) rebaseline
	cd diamondSurf;                                       $(MAKE) rebaseline
	cd airNASA9;                                          $(MAKE) rebaseline
	cd H2_electrode_rxn;                                  $(MAKE) rebaseline
	cd Al_electrode_rxn;                                  $(MAKE) rebaseline
	cd Zn_electrode_rxn; ./rebaseline
	cd KCl_solid_test; ./rebaseline
	cd NaCl_solid_test;                                   $(MAKE) rebaseline
	cd HMW_NaCl_sp_test;                                  $(MAKE) rebaseline
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) rebaseline
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) rebaseline
	cd LiSi_LiCl_electrode_rxn;                           $(MAKE) rebaseline
	cd LiSi_0_LiCl_electrode_rxn;                         $(MAKE) rebaseline
	cd LiSi_2_LiCl_electrode_rxn;                         $(MAKE) rebaseline
	cd LiSi_3_LiCl_electrode_rxn;                         $(MAKE) rebaseline
	cd LiMetal_LiIon_electrode_rxn;                       $(MAKE) rebaseline
	cd MCMBAnode_LiIon_electrode_rxn; ./rebaseline
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./rebaseline
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./rebaseline
	cd FeS_electrode_rxn;                                 $(MAKE) rebaseline
	cd FeS2_electrode_rxn_1;                              $(MAKE) rebaseline
	cd FeS2_electrode_rxn_2;                              $(MAKE) rebaseline
	cd FeS2_electrode_rxn_3;                              $(MAKE) rebaseline
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) rebaseline


clean_dist:
	cd silaneMech;                                        $(MAKE) -s clean_dist
	cd fixedChemPot;                                      $(MAKE) -s clean_dist
	cd heliumAir;                                         $(MAKE) -s clean_dist
	cd issPhase;                                          $(MAKE) -s clean_dist
	cd DHphase;                                           $(MAKE) -s clean_dist
	cd hacaSurf;                                          $(MAKE) -s clean_dist
	cd diamondSurf;                                       $(MAKE) -s clean_dist
	cd airNASA9;                                          $(MAKE) -s clean_dist
	cd H2_electrode_rxn;                                  $(MAKE) -s clean_dist
	cd Al_electrode_rxn;                                  $(MAKE) -s clean_dist
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                   $(MAKE) -s clean_dist
	cd HMW_NaCl_sp_test;                                  $(MAKE) -s clean_dist
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) -s clean_dist
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) -s clean_dist
	cd LiSi_LiCl_electrode_rxn;                           $(MAKE) -s clean_dist
	cd LiSi_0_LiCl_electrode_rxn;                         $(MAKE) -s clean_dist
	cd LiSi_2_LiCl_electrode_rxn;                         $(MAKE) -s clean_dist
	cd LiSi_3_LiCl_electrode_rxn;                         $(MAKE) -s clean_dist
	cd LiMetal_LiIon_electrode_rxn;                       $(MAKE) -s clean_dist
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                 $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_1;                              $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_2;                              $(MAKE) -s clean_dist
	cd FeS2_electrode_rxn_3;                              $(MAKE) -s clean_dist
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) -s clean_dist

clean:
	cd silaneMech;                                        $(MAKE) -s clean
	cd fixedChemPot;                                      $(MAKE) -s clean
	cd heliumAir;                                         $(MAKE) -s clean
	cd issPhase;                                          $(MAKE) -s clean
	cd DHphase;                                           $(MAKE) -s clean
	cd hacaSurf;                                          $(MAKE) -s clean
	cd diamondSurf;                                       $(MAKE) -s clean
	cd airNASA9;                                          $(MAKE) -s clean
	cd H2_electrode_rxn;                                  $(MAKE) -s clean
	cd Al_electrode_rxn; ./cleanup
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                   $(MAKE) -s clean
	cd HMW_NaCl_sp_test;                                  $(MAKE) -s clean
	cd HMW_NaKCl_EQ3_test;                                $(MAKE) -s clean
	cd Li_LiCl_electrode_rxn ;                            $(MAKE) -s clean
	cd LiSi_LiCl_electrode_rxn;                           $(MAKE) -s clean
	cd LiSi_0_LiCl_electrode_rxn;                         $(MAKE) -s clean
	cd LiSi_2_LiCl_electrode_rxn;                         $(MAKE) -s clean
	cd LiSi_3_LiCl_electrode_rxn;                         $(MAKE) -s clean
	cd LiMetal_LiIon_electrode_rxn;                       $(MAKE) -s clean
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                 $(MAKE) -s clean
	cd FeS2_electrode_rxn_1;                              $(MAKE) -s clean
	cd FeS2_electrode_rxn_2;                              $(MAKE) -s clean
	cd FeS2_electrode_rxn_3;                              $(MAKE) -s clean
	cd NewmanFeS2Electrode_rxn;                           $(MAKE) -s clean

clean_test:
	cd silaneMech;                                         $(MAKE) -s clean_test
	cd fixedChemPot;                                       $(MAKE) -s clean_test
	cd heliumAir;                                          $(MAKE) -s clean_test
	cd issPhase;                                           $(MAKE) -s clean_test
	cd DHphase;                                            $(MAKE) -s clean_test
	cd hacaSurf;                                           $(MAKE) -s clean_test
	cd diamondSurf;                                        $(MAKE) -s clean_test
	cd airNASA9;                                           $(MAKE) -s clean_test
	cd H2_electrode_rxn;                                   $(MAKE) -s clean_test
	cd Al_electrode_rxn;                                   $(MAKE) -s clean_test
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                    $(MAKE) -s clean_test
	cd HMW_NaCl_sp_test;                                   $(MAKE) -s clean_test
	cd HMW_NaKCl_EQ3_test;                                 $(MAKE) -s clean_test
	cd Li_LiCl_electrode_rxn ;                             $(MAKE) -s clean_test
	cd LiSi_LiCl_electrode_rxn;                            $(MAKE) -s clean_test
	cd LiSi_0_LiCl_electrode_rxn;                          $(MAKE) -s clean_test
	cd LiSi_2_LiCl_electrode_rxn;                          $(MAKE) -s clean_test
	cd LiSi_3_LiCl_electrode_rxn;                          $(MAKE) -s clean_test
	cd LiMetal_LiIon_electrode_rxn;                        $(MAKE) -s clean_test
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                  $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_1;                               $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_2;                               $(MAKE) -s clean_test
	cd FeS2_electrode_rxn_3;                               $(MAKE) -s clean_test
	cd NewmanFeS2Electrode_rxn;                            $(MAKE) -s clean_test

clean_test_flags:
	cd silaneMech;                                         $(MAKE) -s clean_test_flags
	cd fixedChemPot;                                       $(MAKE) -s clean_test_flags
	cd heliumAir;                                          $(MAKE) -s clean_test_flags
	cd issPhase;                                           $(MAKE) -s clean_test_flags
	cd DHphase;                                            $(MAKE) -s clean_test_flags
	cd hacaSurf;                                           $(MAKE) -s clean_test_flags
	cd diamondSurf;                                        $(MAKE) -s clean_test_flags
	cd airNASA9;                                           $(MAKE) -s clean_test_flags
	cd H2_electrode_rxn;                                   $(MAKE) -s clean_test_flags
	cd Al_electrode_rxn;                                   $(MAKE) -s clean_test_flags
	cd Zn_electrode_rxn; ./cleanup
	cd KCl_solid_test; ./cleanup
	cd NaCl_solid_test;                                    $(MAKE) -s clean_test_flags
	cd HMW_NaCl_sp_test;                                   $(MAKE) -s clean_test_flags
	cd HMW_NaKCl_EQ3_test;                                 $(MAKE) -s clean_test_flags
	cd Li_LiCl_electrode_rxn ;                             $(MAKE) -s clean_test_flags
	cd LiSi_LiCl_electrode_rxn;                            $(MAKE) -s clean_test_flags
	cd LiSi_0_LiCl_electrode_rxn;                          $(MAKE) -s clean_test_flags
	cd LiSi_2_LiCl_electrode_rxn;                          $(MAKE) -s clean_test_flags
	cd LiSi_3_LiCl_electrode_rxn;                          $(MAKE) -s clean_test_flags
	cd LiMetal_LiIon_electrode_rxn;                        $(MAKE) -s clean_test_flags
	cd MCMBAnode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_LiIon_electrode_rxn; ./cleanup
	cd LiCoO2Cathode_2_LiIon_electrode_rxn; ./cleanup
	cd FeS_electrode_rxn;                                  $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_1;                               $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_2;                               $(MAKE) -s clean_test_flags
	cd FeS2_electrode_rxn_3;                               $(MAKE) -s clean_test_flags
	cd NewmanFeS2Electrode_rxn;                            $(MAKE) -s clean_test_flags


