#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             diff_csv.txt  diff_out.txt vcs_equilibrate_res.csv
#
# Create a symbolic link to electrodeCell, if none exists already
#
if test ! -x anode_5_intSurf  ; then
  echo 'ERROR: anode_5_intSurf executable can not be found'
  exit -1
fi

#################################################################
#
#################################################################
MPEQUIL_EXE=${MPEQUIL_EXE:=./anode_5_intSurf}

$MPEQUIL_EXE   > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "$MPEQUIL_EXE returned with bad status, $retnStat, check output"
fi


diff good_out.txt out.txt > diff_out.txt
retnStat_txt=$?

eCode=0
if test $retnStat_txt = "0"
then
  eCode=0
  echo "Successful test comparison on "`pwd`
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnStat_txt != "0"
  then
     echo "      And, text output files have differences. See diff_out.txt"
  fi
fi

#
# return 0 for no errors, 1 for errors
#
exit $eCode

