#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt outa.txt err_out.txt diff_xml.txt  diff_out.txt \
             solution.xml diff_b0.txt diff_b2.txt diff_b2.txt diff_s0.txt diff_s3.txt diff_IV.txt
#
# Create a symbolic link to mpequil, if none exists already
#
if test ! -x LiIon_PorousBat   ; then
  if test -x ../../src_LiIon_PorousBat/LiIon_PorousBat ; then
    ln -s ../../src_LiIon_PorousBat/LiIon_PorousBat .
  else
    echo 'ERROR: Multi1DDomain executable can not be found'
    exit -1
  fi
fi
#
###########################################################################
#
# Specify the MPI environment
#
#MP_MACHINEFILE=${MP_MACHINEFILE:=/home/hkmoffa/arch/linux/lib/machinefile_ceerws0603}
MPIRUN=mpirun
MPIOPTS=""
NP=1
#
###########################################################################
#
XMLSOLNDIFF=${XMLSOLNDIFF:=../../src_test/xmlSolnDiff}
#
#################################################################
#
# Specify the program location
#
MULTI1DDOMAIN_EXE=${MULTI1DDOMAIN_EXE:=LiIon_PorousBat}
#
# Specify the program options
#
PROGRAM_OPTS="LiIon_PorousBat.inp"
#
# Execute the command
#
echo "$MPIRUN $MPIOPTS  -np $NP $MULTI1DDOMAIN_EXE $PROGRAM_OPTS "
# $MPIRUN $MPIOPTS -machinefile $MP_MACHINEFILE -np $NP $MULTI1DDOMAIN_EXE $PROGRAM_OPTS  
$MPIRUN $MPIOPTS  -np $NP $MULTI1DDOMAIN_EXE $PROGRAM_OPTS   > out.txt 2>err_out.txt


