#!/bin/sh

TESTNAME =  MCMBAnode_LiIon_electrode_rxn

BLESSED_FILES = ECsoln_ion.xml  Li_Metal.xml  MCMBAnode_electrode.xml \
     MCMB_RedlichKister.xml  metal_Li_LiIon_electrons.xml problem_setup.sh

include ../Makefile_sub



