#!/bin/sh
#
#
temp_success="1"
testName="gri_matrix_savedEP"
/bin/rm  -f output.txt outputa.txt

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./gri_matrix_savedEP > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="0"
  echo "$testName returned with bad status, $retnStat, check output"
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on gri_matrix_savedEP test"
else
  echo "unsuccessful diff comparison on gri_matrix_savedEP test"
  echo "FAILED" > csvCode.txt
  temp_success="0"
fi

