#!/bin/sh

TESTNAME =  FeS2_3_electrode_rxn

BLESSED_FILES = Fe1_xS.xml  FeS2_3_electrode.xml  Fe_Solid.xml  Li2S.xml  Li2+yFe1-yS2_lattice.xml \
                LiKCl_Margules_trans.xml  LiKCl_recipmoltenSalt_trans.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub


