#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             diff_csv.txt  diff_out.txt vcs_equilibrate_res.csv LiCoO2_intResults_0_0.csv 
#
# Create a symbolic link to electrodeCell, if none exists already
#

PROG_EXE=./LiCoO2_Cathode_3_cc
if test ! -x ${PROG_EXE}  ; then
  echo 'ERROR: ' ${PROG_EXE} ' executable can not be found'
  exit -1
fi

#################################################################
#
#################################################################

$PROG_EXE   > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "$PROG_EXE returned with bad status, $retnStat, check output"
  exit 0
fi

csvdiff  LiCoO2_intResults_blessed.csv   LiCoO2_intResults_0_0.csv  > diff_csv.txt
retnState_csv=$?

diff good_out.txt out.txt > diff_out.txt
retnStat_txt=$?

if test $retnState_csv = "0"
then
  if test $retnStat_txt = "0"
  then
    echo "Successful test comparison on "`pwd`
  else
    echo "Partial successful test but text files differ on "`pwd` " test". See diff_out.txt
  fi
else
  if test $retnStat_txt = "0"
  then
    echo "Unsuccessful comparison of csv  on "`pwd` "test. See diff_csv.txt"
  else
    echo "Unsuccessful comparison of csv and txt files for "`pwd` " test". See diff_out.txt and diff_csv.txt
  fi
  
fi

#
# return 0 for no errors, 1 for errors
#
exit 0
