#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             vcs_Cantera_res.csv \
             diff_csv.txt  diff_out.txt
#
# Create a symbolic link to mpequil, if none exists already
#

#################################################################
#
#################################################################

FeS2_OpenCircuitVoltage  -d 3 > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "mpequil returned with bad status, $retnStat, check output"
fi

csvdiff -a 1.0E-50 ocvOutput_blessed.csv ocvOutput.csv > diff_csv.txt
retnStat_csv=$?

diff  good_out.txt out.txt > diff_out.txt
retnStat_txt=$?

eCode=0
if test $retnStat_csv = "0"
then
  eCode=0
  echo "Successful test comparison on debug "`pwd`
  if [ $retnStat_txt != "0" ]
  then
     echo "   But, text output files have differences. See diff_out.txt"
  fi
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnStat_csv != "0"
  then
     echo "      csv files are different - see diff_csv.txt"
  fi
  if test $retnStat_txt != "0"
  then
     echo "      And, text output files have differences. See diff_out.txt"
  fi
fi

#
# return 0 for no errors, 1 for errors
#
exit 0

