#!/bin/sh

TESTNAME = LiSi_LiCl_electrode_rxn

BLESSED_FILES =   problem_setup.sh Li12Si7.xml  Li13Si4.xml  Li22Si5.xml  Li7Si3.xml \
      LiKCl_Margules.xml  LiKCl_recipmoltenSalt.xml  \
       LiSi_electrode.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub



