#!/bin/sh

TESTNAME = LiSi_0_LiCl_electrode_rxn

BLESSED_FILES =   problem_setup.sh  Li13Si4.xml  Li22Si5.xml  LiKCl_Margules.xml \
      LiKCl_recipmoltenSalt.xml  LiSi_0_electrode.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub



