#!/bin/sh
#
#
/bin/rm  -f output.txt outputa.txt
tName="jp8_matrix"
#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./jp8_matrix > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="1"
  echo "$tName returned with bad status, $retnStat, check output"
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on jp8_matrix test"
  temp_success="0"
else
  echo "unsuccessful diff comparison on jp8_matrix test"
  echo "FAILED" > csvCode.txt
fi
