#!/bin/sh
#
#
#CANTERA_INSTALL_DIR=/home/hkmoffa/arch/CanteraSCON
#CANTERA_INSTALL_DIR=/home/hkmoffa/arch/linux64_gcc444/cantera-1.8_liquidTransportDevelop  
#CANTERA_INSTALL_DIR=/home/hkmoffa/arch/linux64_gcc444/cantera_trunk_dbg
CANTERA_INSTALL_DIR=/home/hkmoffa/arch/linux64_gcc472/cantera_trunk_stable_dbg
#CANTERA_INSTALL_DIR=/home/hkmoffa/arch/linux64_gcc424/cantera-1.8_liquidTransportDevelop_541
export CANTERA_INSTALL_DIR
#
CANTERA_ROOT=/home/hkmoffa/Cantera/gc/cantera_trunk_stable
export CANTERA_ROOT
#
CANTERA_APPS_INSTALL_DIR="${CANTERA_INSTALL_DIR}/apps_stable_dbg"
export CANTERA_APPS_INSTALL_DIR
#
PYTHON_DIR=/home/hkmoffa/arch/linux64_gcc444/python-2.6.4
export PYTHON_DIR
#
#  BUILD_WITH_F2C is optional on linux. 
#
export BUILD_WITH_F2C='n'
#
#
#CANTERA_CONFIG_PREFIX=/home/hkmoffa/arch/linux
#export CANTERA_CONFIG_PREFIX
#
SET_PYTHON_SITE_PACKAGE_TOPDIR=y
export SET_PYTHON_SITE_PACKAGE_TOPDIR
#
PYTHON_SITE_PACKAGE_TOPDIR=/home/hkmoffa/arch/linux64_gcc444/python-2.6.4
export PYTHON_SITE_PACKAGE_TOPDIR
#
CXX=/sierra/sntools/SDK/compilers/gcc/4.7.2-RHEL6/bin/g++

export CXX

# -DDEBUG_MODE
# -DDEBUG_HKM
# -DDO_INIT_CALC
#CXXFLAGS="-g -Wall -DDEBUG_HKM"
CXXFLAGS="-g -Wall -DDEBUG_MODE"
export CXXFLAGS
#
LCXX_END_LIBS=" -lgfortran"
export LCXX_END_LIBS
#
# Specify the fortran compiler, because some libraries are
# written in fortran. This is used to find the libraries
# to link against
#
F77='/sierra/Sntools/extras/compilers/gcc-4.4.4/bin/gfortran'
F77='/sierra/sntools/SDK/compilers/gcc/4.7.2-RHEL6/bin/gfortran'
export F77
#FFLAGS="-g -DDEBUG_HKM  -fno-second-underscore"
FFLAGS="-g -fno-second-underscore"
export FFLAGS

export MPIHOME=/sierra/sntools/SDK/mpi/openmpi/1.6.4-gcc-4.7.2-RHEL6

MPICXX=${MPIHOME}/bin/mpiCC
export MPICXX

MPICC=${MPIHOME}/bin/mpicc
export MPICC

MPIF77=${MPIHOME}/bin/mpif77
export MPIF77

CXX_DEPENDS='/sierra/sntools/SDK/mpi/openmpi/1.6.4-gcc-4.7.2-RHEL6/bin/mpiCC -MM'
# CXX_DEPENDS="${CXX}  -MM"
echo CXX_DEPENDS = $CXX_DEPENDS
export CXX_DEPENDS 

TRILINOS_INSTALL_DIR="/home/hkmoffa/arch/linux64_gcc472/trilinos_10_10_2"
# TRILINOS_INSTALL_DIR="/home/hkmoffa/arch/linux64_gcc444/trilinos_9.0.1_linux_64_dbg"
# TRILINOS_INSTALL_DIR="/home/hkmoffa/arch/linux64_gcc444/trilinos_9.0.1_linux_64_nompi_dbg"
export TRILINOS_INSTALL_DIR

DO_MPI='y'
export DO_MPI

#
MAKE=gmake
export MAKE
#
./preconfig
