#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             diff_csv.txt  diff_out.txt vcs_equilibrate_res.csv
#
# Create a symbolic link to electrodeCell, if none exists already
#

PROG_EXE=HeteroCSTR
if test ! -x ${PROG_EXE}  ; then
  echo 'ERROR: ' ${PROG_EXE} ' executable can not be found'
  exit -1
fi
eCode=0

#################################################################
#
#################################################################

$PROG_EXE   > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "$PROG_EXE returned with bad status, $retnStat, check output"
fi


diff good_out.txt out.txt > diff_out.txt
retnStat_txt=$?

csvdiff  WaterTBP_intResults_0_0_blessed.csv WaterTBP_intResults_0_0.csv > diff_csv.txt
retnStat_csv=$?

if test $retnStat_csv = "0"
then
  echo "Successful test comparison on "`pwd`
  if test $retnStat_txt != "0"
  then
     echo "      But, text output files have differences. See diff_out.txt"
  fi
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnStat_txt != "0"
  then
     echo "      And, text output files have differences. See diff_out.txt"
  fi
fi

#
# return 0 for no errors, 1 for errors
#
exit $eCode

