#/bin/sh

all:
	cd MCMB_Mao;                       	$(MAKE)

test:
	cd MCMB_Mao;                       	$(MAKE) test
	cd MCMBAnode_LiIon_electrode_rxn ;      ./runtest

testd:
	cd MCMB_Mao;                       	$(MAKE) test
	cd MCMBAnode_LiIon_electrode_rxn ;      ./runtest

clean:
	cd MCMB_Mao;                       	$(MAKE) clean
	cd MCMBAnode_LiIon_electrode_rxn ;      ./cleanup

depends:
	cd MCMB_Mao;                       	$(MAKE) depends

install:
	cd MCMB_Mao;                       	$(MAKE) install

