#/bin/sh



all:
#	cd LiKCl_PorousBat_SPCD_MPNewman;               $(MAKE) 

depends:

test:
#	cd LiKCl_PorousBat_SPCD_MPNewman;               $(MAKE) test

clean:
#	cd LiKCl_PorousBat_SPCD_MPNewman;	  	$(MAKE) clean

clean_test:
#	cd LiKCl_PorousBat_SPCD_MPNewman;	  	$(MAKE) test_clean

test_clean:
	$(MAKE) clean_test

clean_test_flags:
#	cd LiKCl_PorousBat_SPCD_MPNewman;         	$(MAKE) clean_testflags

clean_dist:
#	cd LiKCl_PorousBat_SPCD_MPNewman;         	$(MAKE) clean_dist


rebaseline:
#	cd LiKCl_PorousBat_SPCD_MPNewman;         	./rebaseline


install:




