#!/bin/sh

TESTNAME =  FeS2_2_electrode_rxn

BLESSED_FILES = Fe1_xS.xml  FeS2_2_electrode.xml  Li2+yFe1-yS2_lattice.xml  Li3Fe2S4.xml  LiKCl_Margules_trans.xml\
                LiKCl_recipmoltenSalt_trans.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub

rebaseline::
	cp polarizationData.csv polarizationData_blessed.csv


