#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f output.txt outputa.txt

#################################################################
#
#################################################################
CANTERA_DATA=${CANTERA_DATA:=../../data/inputs}; export CANTERA_DATA

CANTERA_BIN=${CANTERA_BIN:=../../bin}
./airNASA9_pairs > output.txt
retnStat=$?
if [ $retnStat != "0" ]
then
  temp_success="1"
  echo "airNASA9_pairs returned with bad status, $retnStat, check output"
fi

diff -w output.txt output_blessed.txt > diff_test.out
retnStat=$?
if [ $retnStat = "0" ]
then
  echo "successful diff comparison on airNASA9_pairs test"
  temp_success="0"
else
  echo "unsuccessful diff comparison on airNASA9_pairs test"
  echo "FAILED" > csvCode.txt
fi

