#!/bin/sh

TESTNAME =  FeS_electrode_rxn

BLESSED_FILES =  FeS2_electrode.xml  FeS2.xml  Li3Fe2S4.xml  LiKCl_Margules.xml\
                 LiKCl_recipmoltenSalt.xml  metal_Li_LiCl_electrons.xml

include ../Makefile_sub



