#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             vcs_eqilibrate_res.csv \
             diff_csv.txt  diff_out.txt

#################################################################
#
#################################################################
VCS_CANTERA_EXE=${VCS_CANTERA_EXE:=gri_equil}
CANTERA_BIN=${CANTERA_BIN:=../../bin}

$VCS_CANTERA_EXE  > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "vcs_Cantera returned with bad status, $retnStat, check output"
fi

diff good_out.txt out.txt  > diff_out.txt
retnStat_txt=$?
csvdiff -a 1.0E-50 vcs_equilibrate_blessed.csv vcs_equilibrate_res.csv  > diff_csv.txt
retnStat_csv=$?

eCode=1 
if test $retnStat_csv = "0"  
then
  eCode=0
  echo "Successful test comparison on "`pwd`
  if [ $retnStat_txt != "0" ]
  then
     echo "   But, text output files have differences. See diff_out.txt"
  fi
else
  echo "Unsuccessful test comparison on "`pwd` " test"
  if test $retnStat_csv != "0"  
  then
     echo "      csv files are different - see diff_csv.txt"
  fi
  if test $retnStat_txt != "0" 
  then
     echo "      And, text output files have differences. See diff_out.txt"
  fi
fi
#
# return 0 for no errors, 1 for errors
#
exit 0
