#!/bin/sh
#
#
temp_success="1"
/bin/rm  -f  out.txt err_out.txt \
             diff_csv.txt  diff_out.txt vcs_equilibrate_res.csv diff_icsv.txt diff_gcsv.txt \
	      MCMB_intResults_0_0.csv  MCMB_globalResults_0_0.csv 
#
# Create a symbolic link to electrodeCell, if none exists already
#

PROG_EXE=./MCMBAnode_CSTR_2
if test ! -x ${PROG_EXE}  ; then
  echo 'ERROR: ' ${PROG_EXE} ' executable can not be found'
  exit -1
fi

#################################################################
#
#################################################################

$PROG_EXE   > out.txt 2>err_out.txt
retnStat=$?
if test $retnStat != "0" 
then
  temp_success="0"
  echo "$PROG_EXE returned with bad status, $retnStat, check output"
fi

csvdiff  MCMB_intResults_blessed_0_0.csv  MCMB_intResults_0_0.csv  > diff_csv.txt
retnStat_icsv=$?

csvdiff  MCMB_globalResults_blessed_0_0.csv  MCMB_globalResults_0_0.csv  > diff_gcsv.txt
retnStat_gcsv=$?

diff good_out.txt out.txt > diff_out.txt
retnStat_txt=$?

retnStat_csv=$retnStat_gcsv
if test $retnStat_icsv != 0
then
  retnStat_csv=$retnStat_icsv
fi

if test $retnStat_csv = "0"
then
  if test $retnStat_txt = "0"
  then
    echo "Successful test comparison on "`pwd`
  else
    echo "Partial Successful test comparison on "`pwd` " but text files differ. See diff_out.txt"
  fi
else
  echo "Unsuccessful test comparison on "`pwd` " test. See diff_icsv.txt and diff_gcsv.txt"
  if  test $retnStat_txt != "0"
  then
     echo "            Text files differ also. See diff_out.txt"
  fi
fi

#
# return 0 for no errors, 1 for errors
#
exit 0

