#!/bin/sh
#
#
#################################################################################################################################
function cleanup {
  if test -e runInProgress.txt
  then
    /bin/rm -f runInProgress.txt
    echo "  Run Interrupted: " `date` > runBad
    /bin/rm -f runGood
  fi
  exit 0
}
#
###############################################################################################################
#
fff='0'
while getopts "fh" opt; do
  case $opt in
    f  ) fff='1' ;;
    h  ) echo 'usage runtest [-f] [-h] [ PROGRAM [ PROGRAM_OPTS] ] '
        exit 1 ;;
    \? ) echo 'usage runtest [-f] [-h] [ PROGRAM [ PROGRAM_OPTS] ]'
        exit 1 ;;
  esac
done
#
###############################################################################################################
#
#  Check the file flag to see if a run is in progress
#
if test -f runInProgress.txt
then
  if test $fff == '0'
  then
    echo 'Runner ' $$ ': Test skipped due to runInProgress.txt flag: ' `pwd`
    echo '               Remove the flag file if you want to run the test'
    exit 0
  fi
fi
echo $$ > runInProgress.txt
#
#  trap interrupt and signals. 
#
trap cleanup INT TERM TSTP QUIT
#
#############################################################################################################
temp_success="1"
/bin/rm  -f  out.txt err_out.txt diff_csv.txt  diff_out.txt diff_tout.txt  \
             thermo.csv MCMBThermo.out MCMB.out
#
##################################################################################################################################
#
export ELECTRODE_TURN_OFF_PC_PRINTING=true

MCMB > MCMB.out 2>err_out.txt
retnStat=$?
if test $retnStat != "0"
then
  temp_success="0"
  echo "MCMB returned with bad status, $retnStat, check output"
fi

diff MCMB_blessed.out MCMB.out > diff_tout.txt
retnStat_txt=$?

if test $retnStat_txt != "0"
then
  echo "Unsuccessful test comparison on "`pwd` " text files differ. See diff_out.txt"
fi
#
#  Release the semiphore
#
/bin/rm runInProgress.txt
#
# return 0 for no errors, 1 for errors
#
exit 0
