#!/bin/sh

TESTNAME = LiCoO2Cathode_LiIon_electrode_rxn

BLESSED_FILES =  ECsoln_ion.xml  LiCoO2Cathode_electrode.xml \
  LiCoO2_RedlichKister.xml  metal_Li_LiIon_electrons.xml problem_setup.sh

include ../Makefile_sub



