#!/bin/sh

TESTNAME = H2_electrode_rxn

BLESSED_FILES = problem_setup.sh h2gas.xml  HMW_NaCl_sp1977_alt.xml  Pt_electrode.xml

include ../Makefile_sub

rebaseline::
	cp polarizationData.csv polarizationData_good.csv



