#!/bin/sh

TESTNAME = LiCoO2Cathode_2_LiIon_electrode

BLESSED_FILES =  ECsoln_ion.xml  LiCoO2Cathode_electrode.xml\
                 LiCoO2_Margules_1.xml  metal_Li_LiIon_electrons.xml\
                 problem_setup.sh

include ../Makefile_sub



